
USE WAREHOUSE WH_DEV;

USE ROLE SF_DEV_WRITE;

SELECT * FROM MAROOCHYDORE.MYD_SALES 
WHERE "VENUE" = 'Homemaker' and "SALES" = 10000;

SELECT * FROM CALOUNDRA.CLDA_SALES;

//Move into stages

COPY INTO @MAROOCHYDORE.%MYD_SALES
FROM MAROOCHYDORE.MYD_SALES;

LIST @MAROOCHYDORE.%MYD_SALES; 

REMOVE @MAROOCHYDORE.%MYD_SALES;

LIST @MAROOCHYDORE.%MYD_SALES; 

COPY INTO @CALOUNDRA.%CLDA_SALES
FROM MAROOCHYDORE.MYD_SALES;

LIST @CALOUNDRA.%CLDA_SALES;

REMOVE @CALOUNDRA.%CLDA_SALES;

USE SCHEMA CALOUNDRA; // do not use INFORMATION SCHEMA

CREATE OR REPLACE STAGE SUNSHINE_STAGE
    directory = (enable = true)
    copy_options = (on_error = 'skip_file')
    comment = 'example of named internal stage';

COPY INTO @SUNSHINE_STAGE // Copy into created stage using internal stage
FROM CALOUNDRA.CLDA_SALES; 

SELECT * FROM DIRECTORY(@SUNSHINE_STAGE); // Directory is true

ALTER STAGE SUNSHINE_STAGE REFRESH; // refresh the directory

REMOVE @SUNSHINE_STAGE;
SHOW STAGES IN DATABASE SUNCARE_TEST;

DESCRIBE STAGE SUNSHINE_STAGE;