USE DATABASE SUNCARE_TEST;

//CREATE OR REPLACE SCHEMA CRYPTO;

USE WAREHOUSE WH_DEV;

USE SCHEMA CRYPTO;

USE ROLE SYSADMIN;

USE ROLE SUNCARE_TEST_WRITE;

SHOW GRANTS ON DATABASE SUNCARE_TEST;

SHOW GRANTS ON SCHEMA CRYPTO;

SHOW GRANTS ON TABLE CRYPTO_PRICES;

GRANT USAGE ON SCHEMA CRYPTO TO ROLE SUNCARE_TEST_WRITE;
GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE SUNCARE_TEST_WRITE;
GRANT USAGE ON DATABASE SUNCARE_TEST TO ROLE SUNCARE_TEST_WRITE;
GRANT INSERT, UPDATE, DELETE, SELECT ON TABLE CRYPTO_PRICES TO ROLE SUNCARE_TEST_WRITE;


CREATE OR REPLACE STAGE COINGECKO
FILE_FORMAT = (TYPE = JSON)
    directory = (enable = true)
    copy_options = (on_error = 'skip_file')
    comment = 'Gecko coin internal stage';

SHOW STAGES;

CREATE OR REPLACE TABLE CRYPTO_PRICES(
    currency VARCHAR,
    price FLOAT
);

SHOW TABLE CRYPTO_PRICES;

//URL FOR FREE API: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd

SELECT* FROM CRYPTO_PRICES;
