USE DATABASE SUNCARE_TEST;

USE SCHEMA KEYLOST;

USE WAREHOUSE WH_DEV;

USE ROLE SYSADMIN;

--table1
CREATE OR REPLACE TABLE SUNCARE_TEST.KEYLOST.ORDER_EX(
ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
);

-- Example transformations 1--
COPY INTO SUNCARE_TEST.KEYLOST.ORDER_EX
FROM (SELECT s.$1, s.$2 FROM @EXTERNAL_AWS_STAGE s)
FILE_FORMAT = MY_CSV_FF
FILES = ('OrderDetails.csv');


--table2--
CREATE OR REPLACE TABLE SUNCARE_TEST.KEYLOST.ORDER_EX(
ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    PROFITABLE_FLAG VARCHAR);

--example transformation 2--

COPY INTO SUNCARE_TEST.KEYLOST.ORDER_EX
FROM (SELECT
        s.$1,
        s.$2,
        s.$3,
        CASE WHEN CAST (s.$3 as INT) < 0 THEN 'Not profitable' ELSE 'profitable' END
    FROM @EXTERNAL_AWS_STAGE s)
FILE_FORMAT = MY_CSV_FF
FILES = ('OrderDetails.csv');
;


--table 3--
CREATE OR REPLACE TABLE SUNCARE_TEST.KEYLOST.ORDER_EX(
ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    CATEGORY_SUBSTRINT VARCHAR);

--trandformations 3

COPY INTO SUNCARE_TEST.KEYLOST.ORDER_EX
FROM ( SELECT 
        s.$1,
        s.$2,
        s.$3,
        SUBSTRING(S.$5,1,5)
        FROM @EXTERNAL_AWS_STAGE s)
    FILE_FORMAT = MY_CSV_FF
    FILES = ('OrderDetails.csv');


----table 4----

CREATE OR REPLACE TABLE SUNCARE_TEST.KEYLOST.ORDER_EX(
ORDER_ID VARCHAR(30),
    AMOUNT INT,
    PROFIT INT,
    CATEGORY_SUBSTRINT VARCHAR);

--transformation 4

COPY INTO SUNCARE_TEST.KEYLOST.ORDER_EX (ORDER_ID, PROFIT)
FROM (SELECT
        s.$1,
        s.$3,
        FROM @EXTERNAL_AWS_STAGE s)
    FILE_FORMAT = MY_CSV_FF
    FILES = ('OrderDetails.csv')        
; 

SELECT * FROM SUNCARE_TEST.KEYLOST.ORDER_EX;